from .zwng_nodes import NODE_CLASS_MAPPING, NODE_DISPLAY_NAME_MAPPING

NODE_CLASS_MAPPINGS={}
NODE_DISPLAY_NAME_MAPPINGS={}

NODE_CLASS_MAPPINGS.update(zwng_nodes.NODE_CLASS_MAPPING)
NODE_DISPLAY_NAME_MAPPINGS.update(zwng_nodes.NODE_DISPLAY_NAME_MAPPING)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']